//getters
export const PRODUCT_COUNT_IN_WISHLIST = "PRODUCT_COUNT_IN_WISHLIST";
export const PRODUCT_IN_WISHLIST = "PRODUCT_IN_WISHLIST";

//mutations
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const LOG_OUT = "LOG_OUT";
