//mutations
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART ='REMOVE_FROM_CART'
export const BUY_PRODUCT = 'BUY_PRODUCT'
export const ADD_TO_CART_FROM_WISHLIST='ADD_TO_CART_FROM_WISHLIST'
export const LOG_OUT='LOG_OUT'

//getters
export const PRODUCT_IN_CART ='PRODUCT_IN_CART'
export const PRODUCT_COUNT_IN_CART ='PRODUCT_COUNT_IN_CART'
